language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    # Latest dependencies with all PHP versions
    - php: 7.2
    - php: 7.3
    - php: 7.4

      # Ignore the platform requirements for the upcoming PHP version
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction $COMPOSER_FLAGS

script:
  - mkdir tools build;
  - composer test;
 
after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - danny.vandersluijs@icloud.com