#!/usr/bin/env php
<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    die('Warning: WsdlToClass should be invoked via the CLI version of PHP, not the ' . PHP_SAPI . ' SAPI' . PHP_EOL);
}

/**
 * This makes our life easier when dealing with paths. Everything is relative
 * to the application root now.
 */
chdir(__DIR__);

$autoLoaderFiles = array('vendor/autoload.php', '../autoload.php', '../../autoload.php');

foreach ($autoLoaderFiles as $autoLoaderFile) {
    if (is_readable($autoLoaderFile)) {
        $loader = include $autoLoaderFile;
        break;
    }
}

if (!$loader) {
    die('You must set up the project dependencies.');
}

// set to run indefinitely if needed
set_time_limit(0);

/* Optional. It’s better to do it in the php.ini file */
date_default_timezone_set('Europe/Amsterdam');

$app = new \Symfony\Component\Console\Application();
$app->add(new \WsdlToClass\Command\GenerateCommand());
$app->run();
