#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
    echo 'Warning: Composer should be invoked via the CLI version of PHP, not the '.PHP_SAPI.' SAPI'.PHP_EOL;
}

if (!$loader = include __DIR__ . '/vendor/autoload.php' || !$loader = include __DIR__ . '/../../autoload.php') {
    die('You must set up the project dependencies.');
}

// set to run indefinitely if needed
set_time_limit(0);

/* Optional. It’s better to do it in the php.ini file */
date_default_timezone_set('Europe/Amsterdam');

$app = new \Cilex\Application('Cilex');
$app->command(new \WsdlToClass\Commands\ImportCommand());
$app->run();
