<?php
namespace WsdlToClass\Wsdl;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-22 at 18:45:57.
 */
class RequestTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Request;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers WsdlToClass\Wsdl\Request::createFromStruct
     */
    public function testCreateFromStruct()
    {
        $struct = $this->getMock('WsdlToClass\Wsdl\Struct');
        $struct->expects($this->once())->method('getName')->willReturn('ExampleRequest');
        $struct->expects($this->once())->method('getProperties')->willReturn(array());
        $request = Request::createFromStruct($struct);

        $this->assertInstanceOf('WsdlToClass\Wsdl\Request', $request);
        $this->assertSame($request->getName(), 'ExampleRequest');
        $this->assertSame($request->getProperties(), array());

    }
}
