<?php
namespace WsdlToClass\Wsdl;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-22 at 18:45:55.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers WsdlToClass\Wsdl\Response::createFromStruct
     */
    public function testCreateFromStruct()
    {
        $struct = $this->getMock('WsdlToClass\Wsdl\Struct');
        $struct->expects($this->once())->method('getName')->willReturn('ExampleResponse');
        $struct->expects($this->once())->method('getProperties')->willReturn(array());
        $request = Response::createFromStruct($struct);

        $this->assertInstanceOf('WsdlToClass\Wsdl\Response', $request);
        $this->assertSame($request->getName(), 'ExampleResponse');
        $this->assertSame($request->getProperties(), array());
    }
}
