<?php

namespace WsdlToClass\Wsdl;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-08 at 21:15:16.
 */
class WsdlTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Wsdl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Wsdl('http://www.w3schools.com/webservices/tempconvert.asmx?WSDL');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::getSource
     */
    public function testGetSource()
    {
        $this->assertSame('http://www.w3schools.com/webservices/tempconvert.asmx?WSDL', $this->object->getSource());
        $this->object->setSource('http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL');
        $this->assertSame('http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL', $this->object->getSource());
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::setSource
     */
    public function testSetSource()
    {
        $this->assertSame($this->object, $this->object->setSource('http://www.webservicex.net/CurrencyConvertor.asmx?WSDL'));
        $this->assertAttributeSame('http://www.webservicex.net/CurrencyConvertor.asmx?WSDL', 'source', $this->object);
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::addStruct
     * @todo   Implement testAddStruct().
     */
    public function testAddStruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::getStructures
     * @todo   Implement testGetStructures().
     */
    public function testGetStructures()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::getStruct
     * @todo   Implement testGetStruct().
     */
    public function testGetStruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::addMethod
     * @todo   Implement testAddMethod().
     */
    public function testAddMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::getMethods
     * @todo   Implement testGetMethods().
     */
    public function testGetMethods()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::addRequest
     * @todo   Implement testAddRequest().
     */
    public function testAddRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::getRequests
     * @todo   Implement testGetRequests().
     */
    public function testGetRequests()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::hasRequest
     * @todo   Implement testHasRequest().
     */
    public function testHasRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::addResponse
     * @todo   Implement testAddResponse().
     */
    public function testAddResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::getResponses
     * @todo   Implement testGetResponses().
     */
    public function testGetResponses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::hasResponse
     * @todo   Implement testHasResponse().
     */
    public function testHasResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::__toString
     */
    public function test__toString()
    {
        $this->object->setSource('http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL');
        $this->assertSame('http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL', (string) $this->object);
    }

    /**
     * @covers WsdlToClass\Wsdl\Wsdl::visit
     */
    public function testVisit()
    {
        $mock = $this->getMock('WsdlToClass\Generator\IServiceGenerator');
        $mock->expects($this->once())->method('generateService')->with($this->object)->willReturn('<?php echo "Hello world!"; ');
        $this->assertSame('<?php echo "Hello world!"; ', $this->object->visit($mock));
    }

}
