<?php

namespace WsdlToClass\Writer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-16 at 19:28:46.
 */
class ResourceWriterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ResourceWriter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ResourceWriter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WsdlToClass\Writer\ResourceWriter::writeFile
     * @todo   Implement testWriteFile().
     */
    public function testWriteFile()
    {
        $filename = tempnam(sys_get_temp_dir(), 'phpunit_');
        $content = 'Random data 42';
        $this->object->writeFile($filename, $content);
        $this->assertFileExists($filename);
        $this->assertEquals($content, file_get_contents($filename));
    }

}
