<?php

namespace WsdlToClass\Parser;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-07 at 17:43:57.
 */
class RegexParserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PhpInternalStructParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RegexParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WsdlToClass\Parser\RegexParser::parseType
     */
    public function testParseType()
    {
        $result = $this->object->parseType(<<<EOT
struct ProductLine {
 string Mode;
 string RelevanceRank;
}
EOT
);
        $this->assertInstanceOf('WsdlToClass\Wsdl\Struct', $result);
        $this->assertSame('ProductLine', $result->getName());
        $this->assertTrue($result->hasProperty('Mode'));
        $this->assertTrue($result->hasProperty('RelevanceRank'));
        $this->assertSame('string', $result->getProperty('Mode')->getType());
        $this->assertSame('Mode', $result->getProperty('Mode')->getName());
        $this->assertSame('string', $result->getProperty('RelevanceRank')->getType());
        $this->assertSame('RelevanceRank', $result->getProperty('RelevanceRank')->getName());
    }

    /**
     * @covers WsdlToClass\Parser\RegexParser::parseFunction
     */
    public function testParseFunction()
    {
        $result = $this->object->parseFunction('Address getAddress(Postcode $postcode)');
        $this->assertInstanceOf('WsdlToClass\Wsdl\Method', $result);
        $this->assertSame('getAddress', $result->getName());
        $this->assertSame('Postcode', $result->getRequest());
        $this->assertSame('Address', $result->getResponse());
    }

}
