<?php

namespace WsdlToClass\Generator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-08 at 19:27:03.
 */
class AbstractGeneratorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TwigGenerator();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers WsdlToClass\Generator\AbstractGenerator::getNamespace
     */
    public function testGetNamespace()
    {
        $this->assertNull($this->object->getNamespace());
        $this->object->setNamespace('\Soap\Messages');
        $this->assertSame('\Soap\Messages', $this->object->getNamespace());
    }

    /**
     * @covers WsdlToClass\Generator\AbstractGenerator::setNamespace
     */
    public function testSetNamespace()
    {
        $this->assertSame($this->object, $this->object->setNamespace('\Soap\Method'));
        $this->assertAttributeSame('\Soap\Method', 'namespace', $this->object);
    }

}
