<?php
namespace WsdlToClass\Generator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-22 at 18:46:00.
 */
class TwigGeneratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TwigGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TwigGenerator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers WsdlToClass\Generator\TwigGenerator::generateClassMap
     * @todo   Implement testGenerateClassMap().
     */
    public function testGenerateClassMap()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Generator\TwigGenerator::generateStruct
     * @todo   Implement testGenerateStruct().
     */
    public function testGenerateStruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Generator\TwigGenerator::generateService
     * @todo   Implement testGenerateService().
     */
    public function testGenerateService()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Generator\TwigGenerator::generateMethod
     * @todo   Implement testGenerateMethod().
     */
    public function testGenerateMethod()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WsdlToClass\Generator\TwigGenerator::generateClient
     * @todo   Implement testGenerateClient().
     */
    public function testGenerateClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
